# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        img:
            uri_prefix: /assets/img
            upload_destination: '%kernel.project_dir%/public/assets/img'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true